Remove automatic create_database() call
This avoids an IntegrityError when create_database() is called at the
same time in two different scripts.

I.e.:
sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) duplicate key value violates unique constraint "pg_type_typname_nsp_index"